### ISSUE TITLE
Installation Error PHP 8.1

### ISSUE THREAD

**Issue by PauloBoaventura** [AranduTech/laravel-mui-admin#1]
TypeError
method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given (View: /home/SITE.COM/public_html/resources/views/layouts/app.blade.php)

.
**= Stack Trace =** 
app/Services/React.php:161

` 

    public function all()

    {

        return collect($this->data)

     #  LINE 161 =>> ###         ->map(fn ($value) => method_exists($value, 'toArray')

                ? $value->toArray()

                : $value);

    }`

**Comment by PauloBoaventura** [comment]
Hi, @obrunopolo 

Could you give a reference, more precise about this problem?
In my searches I found a Bug with Php 8.0.
As it is recommended to install php 7.4 this has become a problem
Because php7.4 is out of use and previous versions of php are not being installed on Linux.

**Comment by obrunopolo** [comment]
Hello @PauloBoaventura 
This project is being built on top of php 7.4. There are plans to make it compatible with php 8+, and laravel 9/10. 
At this moment I'm focused in building core functionalities and documentation, and could not test compatibility yet.

I'll look into a fix. Its not expected `$value` to be an `array`.

**Comment by obrunopolo** [comment]
> Hi, @obrunopolo
> 
> Could you give a reference, more precise about this problem? In my searches I found a Bug with Php 8.0. As it is recommended to install php 7.4 this has become a problem Because php7.4 is out of use and previous versions of php are not being installed on Linux.

Pull latest commit from master and see if it fixes

**Comment by PauloBoaventura** [comment]
my incompatibility reference...
It can help...

[https://github.com/LaravelCollective/html/pull/671](https://github.com/LaravelCollective/html/pull/671)

**Comment by obrunopolo** [comment]
> my incompatibility reference... It can help...
> 
> [LaravelCollective/html#671](https://github.com/LaravelCollective/html/pull/671)

did you see my last response? Its probably fixed now

**Comment by PauloBoaventura** [comment]
> > my incompatibility reference... It can help...
> > [LaravelCollective/html#671](https://github.com/LaravelCollective/html/pull/671)
> 
> did you see my last response? Its probably fixed now


Yes!! 

I ran Pull latest commit as instructed. But due to being using php8.1. I got the same error.


- [X] Solution:

Ubuntu 22.04.2 LTS
Nginx


Installed the php7.4-fpm version and its extensions.

     $:    LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php && apt-get update

     $:    apt-get install php7.4-{cgi,cli,fpm,pdo,gd,mbstring,mysqlnd,opcache,xml,zip}

     $:    sudo apt-get install  php7.4 php7.4-cli php7.4-common php7.4-fpm php7.4-mysql php7.4-zip php7.4-gd php7.4-mbstring php7.4-curl php7.4-xml php7.4-bcmath openssl php7.4-json php7.4-tokenizer`
     

It replaces the PHP configuration to be used only in this Domain.

And ready. Everything solved.
